variables:
  DEFAULT_NODE_VERSION: "12.x"


pool:
  vmImage: "macOS-10.15"


parameters:
- name: testJobs
  type: object
  default:
  - iosVersion: 12
    xcodeVersion: 10
    iosDeviceName: iPhone 6
    vmImage: macOS-10.14
  - iosVersion: 12.4
    xcodeVersion: 10.3
    iosDeviceName: iPhone X
    vmImage: macOS-10.14  
  - xcodeVersion: 10.3
    deviceName: iPhone X
    vmImage: macOS-10.14
  - xcodeVersion: 11.2
    deviceName: iPhone 11
    vmImage: macOS-10.15
  - xcodeVersion: 11.7
    deviceName: iPhone 11
    vmImage: macOS-10.15
  - xcodeVersion: 12
    deviceName: iPhone 11
    vmImage: macOS-10.15


stages:
- stage: node-simctl_Unit_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./packages/node-simctl/.azure-templates/base_unit_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        xcodeVersion: ${{ job.xcodeVersion }}
        vmImage: ${{ job.vmImage }}

- stage: node-simctl_Integration_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./packages/node-simctl/.azure-templates/base_integration_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        xcodeVersion: ${{ job.xcodeVersion }}
        deviceName: ${{ job.deviceName }}
        vmImage: ${{ job.vmImage }}

- stage: ios-simulator_Unit_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./packages/ios-simulator/azure-templates/base_unit_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        xcodeVersion: ${{ job.xcodeVersion }}
        vmImage: ${{ job.vmImage }}

- stage: ios-simulator_Integration_Test
  jobs:
  - ${{ each job in parameters.testJobs }}:
    - template: ./packages/ios-simulator/azure-templates/base_integration_test_job.yml
      parameters:
        name: Xcode_${{ replace(job.xcodeVersion, '.', '_') }}_iOS_${{ replace(job.iosVersion, '.', '_') }}
        iosVersion: ${{ job.iosVersion }}
        xcodeVersion: ${{ job.xcodeVersion }}
        iosDeviceName: ${{ job.iosDeviceName }}
        vmImage: ${{ job.vmImage }}


# from ios-test-app

# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: macOS-10.15

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: "12.x"
# - script: sudo xcode-select --switch "/Applications/Xcode_11.6.app/Contents/Developer"
# - script: npm install
#   displayName: Xcode 11.6
# - script: sudo xcode-select --switch "/Applications/Xcode_12.4.app/Contents/Developer"
# - script: npm install
#   displayName: Xcode 12.4
