export const DEFAULT_APPLETV_PAIRING_DISCOVERY_TIMEOUT_MS = Number(process.env.APPLETV_DISCOVERY_TIMEOUT) || 10_000;
export const DEFAULT_WIRELESS_APPLETV_DISCOVERY_TIMEOUT_MS = 10_000;
export const DEFAULT_TUNNEL_REGISTRY_PORT = 42314;
