name: ios-uicatalog CI
on:
  pull_request:
    paths: ['packages/ios-uicatalog/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ios-uicatalog-build-app.yml
    with:
      upload_pr_artifacts: ${{ github.event_name == 'pull_request' }}
      run_lint: true
