# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  common:
    name: Common checks (Node.js v${{ matrix.node-version }})
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npm run test:common

  ios-simulator:
    name: ios-simulator checks (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
    runs-on: macos-latest
    strategy:
      matrix:
        device-name: [iPhone 12, iPhone 11]
        xcode-version: [12.4, 12.3, 11.7]
        include:
          - device-name: iPhone 12
            ios-version: 14.4
          - device-name: iPhone 11
            ios-version: 13.7
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/applesimutils--*
            ~/Library/Caches/Homebrew/downloads/*--applesimutils-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Update Homebrew
        run: |
          brew tap wix/brew
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/wix/homebrew-brew/applesimutils.rb" > .github/brew-formulae
      - name: Install Homebrew dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: brew install applesimutils
      - name: Tests (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
        run: scripts/test-ios-simulator.sh
        env:
          XCODE_VERSION: ${{ matrix.xcode-version }}
          MOBILE_DEVICE_NAME: ${{ matrix.device-name }}
          MOBILE_OS_VERSION: ${{ matrix.ios-version }}
