# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  common:
    name: Common tests (Node.js v${{ matrix.node-version }})
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npm run test:common

  ios-simulator_unit:
    name: ios-simulator unit tests (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        include:
          - device-name: iPhone 12
            xcode-version: 12.4
            ios-version: 14.4
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Unit Tests (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
        run: |
          sudo xcode-select --switch "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"
          npm run test:ios-simulator
        env:
          XCODE_VERSION: ${{ matrix.xcode-version }}
          MOBILE_DEVICE_NAME: ${{ matrix.device-name }}
          MOBILE_OS_VERSION: ${{ matrix.ios-version }}

  ios-simulator_e2e:
    name: ios-simulator e2e tests (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
    runs-on: macos-latest
    needs: [ios-simulator_unit]
    strategy:
      matrix:
        include:
          - device-name: iPhone 12
            xcode-version: 12.4
            ios-version: 14.4
          - device-name: iPhone 12
            xcode-version: 12.3
            ios-version: 14.3
          - device-name: iPhone 11
            xcode-version: 11.7
            ios-version: 13.7
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/applesimutils--*
            ~/Library/Caches/Homebrew/downloads/*--applesimutils-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Update Homebrew
        run: |
          brew tap wix/brew
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/wix/homebrew-brew/applesimutils.rb" > .github/brew-formulae
      - name: Install Homebrew dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: brew install applesimutils
      - name: E2E Tests (Node.js v${{ matrix.node-version }} / iOS v${{ matrix.ios-version }} / Xcode v${{ matrix.xcode-version }} / ${{ matrix.device-name }})
        run: |
          sudo xcode-select --switch "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"
          npm run test:e2e:ios-simulator
        env:
          XCODE_VERSION: ${{ matrix.xcode-version }}
          MOBILE_DEVICE_NAME: ${{ matrix.device-name }}
          MOBILE_OS_VERSION: ${{ matrix.ios-version }}
